//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pseudocode_Master.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pseudocode_Master.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Blinking_exclamation_mark {
            get {
                object obj = ResourceManager.GetObject("Blinking_exclamation_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap builder {
            get {
                object obj = ResourceManager.GetObject("builder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Check {
            get {
                object obj = ResourceManager.GetObject("Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap codechecker {
            get {
                object obj = ResourceManager.GetObject("codechecker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cin&gt;&gt;
        ///cout&lt;&lt;
        ///{
        ///}
        ///unsigned int
        ///int
        ///float
        ///float
        /// ==
        /// !=
        /// /
        /// %
        /// &amp;&amp;
        /// ||
        /// !
        /// =
        /// do
        /// while.
        /// </summary>
        public static string cplusplus {
            get {
                return ResourceManager.GetString("cplusplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap declaration {
            get {
                object obj = ResourceManager.GetObject("declaration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read
        ///write
        ///declare
        ///assign
        ///if
        ///then
        ///else
        ///for
        ///while
        ///do
        ///repeat/until
        ///endif
        ///endwhile
        ///endfor
        ///
        ///Welcome to Pseudocode Learning Companion
        ///Please select an option:
        ///Translator
        ///Learning Environment
        ///Builder
        ///Code Checker
        ///Help
        ///Program made using Visual C# 2015
        ///Copyright (c) 2015 Catalin Popa
        ///
        ///Translate now !
        ///Check now !
        ///Select the instruction that you wish to learn 
        ///General statement: (attention! write only one statement, using the given syntax)
        ///Show details
        ///Hide details
        ///Thank you for using  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HALP {
            get {
                object obj = ResourceManager.GetObject("HALP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap learning {
            get {
                object obj = ResourceManager.GetObject("learning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Learning_Envorinment {
            get {
                object obj = ResourceManager.GetObject("Learning_Envorinment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MI {
            get {
                object obj = ResourceManager.GetObject("MI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MI_E {
            get {
                object obj = ResourceManager.GetObject("MI_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lire
        ///ecrire
        ///declarer
        ///assignant
        ///si
        ///puis
        ///autre
        ///pour
        ///tandis que
        ///faire
        ///repeter / jusqu&apos;a ce que
        ///fin.si
        ///fin.tandis que
        ///fin.pour
        ///
        ///Bienvenue a Pseudocode Learning Companion
        ///Veuillez selectionner une option:
        ///Traducteur
        ///Environnement d&apos;apprentissage
        ///Constructeur
        ///code de Checker
        ///Aidez-moi
        ///Programme faite en utilisant Visual C # 2015
        ///Copyright (c) 2015 Catalin Popa
        ///
        ///Traduire maintenant!
        ///Verifiez maintenant !
        ///Selectionnez l&apos;instruction que vous souhaitez apprendre
        ///Declaration generale: (atte [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OTHER {
            get {
                return ResourceManager.GetString("OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read(
        ///write(
        ///begin
        ///end
        ///integer
        ///integer
        ///real
        ///real
        /// =
        /// &lt;&gt;
        /// DIV
        /// MOD
        /// AND
        /// OR
        /// NOT
        /// :=
        /// repeat
        /// until.
        /// </summary>
        public static string pascal {
            get {
                return ResourceManager.GetString("pascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to citeste
        ///scrie
        ///declara
        ///atribuire
        ///daca
        ///atunci
        ///altfel
        ///pentru
        ///cat timp
        ///executa
        ///repeta/pana cand
        ///sf.daca
        ///sf.cat timp
        ///sf.pentru
        ///
        ///Bun venit in Pseudocode Learning Companion
        ///Selecteaza optiunea dorita:
        ///Traducator
        ///Mediu de invatare
        ///Builder
        ///Verificator de cod
        ///Ajutor
        ///Program realizat in Visual C# 2015
        ///Copyright (c) 2015 Catalin Popa
        ///
        ///Tradu acum !
        ///Verifica acum !
        ///Selecteaza instructiunea pe care doresti sa o inveti.
        ///Forma generala: (atentie! se scrie o singura instructiune, numai in sintaxa  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TR {
            get {
                object obj = ResourceManager.GetObject("TR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TR_E {
            get {
                object obj = ResourceManager.GetObject("TR_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap translator {
            get {
                object obj = ResourceManager.GetObject("translator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tree_Alone {
            get {
                object obj = ResourceManager.GetObject("Tree_Alone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VC {
            get {
                object obj = ResourceManager.GetObject("VC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VC_E {
            get {
                object obj = ResourceManager.GetObject("VC_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
